name: Test Action Workflow
on: 
  push:
    branches: [main]
        
jobs:
  run-action:
    name: 'run the action'
    uses: actions/setup-node@v4.0.0
    with:
        who-to-greet: ${{ inputs.who-to-greet }}
