name: GitHub Actions Demo
on: 
  workflow_dispatch:
  push:
    branches: main
    paths-ignore: '.github'
  pull_request:
    types: [merged]
    branches: main
  schedule:
    - cron: '15 6 * * 0'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Output event name
        run: echo '${{github.event_name}}'
      - name: Output branch name
        run: echo '${{github.ref_name}}'

