name: GitHub Actions Demo
on: 
  workflow_dispatch:
  push:
    branches: [main]
    paths: []
  pull_request:
  schedule:
    - cron: '15 6 * * 0'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3.30
      - name: Test 1
        run: echo '${{toJSON(github)}}'
      - name: Test 2
        run: echo ''

