name: GitHub Actions Demo
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Env to deploy to'
        type: environment
        required: true
  push:
    branches: main
    paths-ignore: '.github'
  pull_request:
    types: [merged]
    branches: main
  schedule:
    - cron: '15 6 * * 0'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
          
  Test:
    runs-on: ubuntu-latest
    needs: [Build]
    if: github.event_name == 'workflow_dispatch'
    environment: Test
    steps:
      - name: Type testing
        run: echo 'testing...'

  Load-Test:
    runs-on: ubuntu-latest
    needs: [Build]
    if: github.event_name == 'workflow_dispatch'
    environment: Load-Test
    steps:
      - name: write testing
        run: |
          echo 'testing...'
          sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    if: github.event_name == 'workflow_dispatch'
    environment:
      name: Production
      url: https://writeabout.net
    steps:
      - run: 
          echo 'Step 1 deploying'
          sleep 10
      - run: 
          echo 'Step 2 deploying'
          sleep 10
      - run: 
          echo 'Step 3 deploying'
          sleep 10
      - run: 
          echo 'Step 4 deploying'
          sleep 10
      - run: 
          echo 'Step 5 deploying'
          sleep 10
        
    
 
      

