name: 'Test Action Workflow'
on: 
  push:
    branches: [main]
        
jobs:
  run-action:
    name: 'run the action'
    uses: actions/hello-world-action@main
    with:
        who-to-greet: ${{ inputs.who-to-greet }}
